apiVersion: apps/v1
kind: Deployment
metadata:
  name: senkongdao-app
  labels:
    app: senkongdao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: senkongdao
  template:
    metadata:
      labels:
        app: senkongdao
    spec:
      containers:
      - name: senkongdao-app
        image: senkongdao:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: senkongdao-secrets
              key: mongo-uri
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: senkongdao-service
spec:
  selector:
    app: senkongdao
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP